## Import

In [2]:
import pandas as pd
from sklearn import metrics
import numpy as np
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D
from keras.layers import Dense, Dropout
import os
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.metrics import f1_score
from keras import optimizers
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import KFold
import seaborn as sns

import os
import operator
import time
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from sklearn.model_selection import cross_val_score
from keras.layers import Conv1D, Conv2D, Dense, Dropout, BatchNormalization, Flatten, MaxPooling1D
from keras.layers import Dense, Dropout
#from keras.utils import np_utils
from keras import utils
from keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adagrad, Adamax, Nadam, Ftrl
from keras.callbacks import EarlyStopping, ModelCheckpoint
#from keras.wrappers.scikit_learn import KerasClassifier
from scikeras.wrappers import KerasRegressor
from math import floor
from sklearn.metrics import make_scorer, accuracy_score
from bayes_opt import BayesianOptimization
from sklearn.model_selection import StratifiedKFold
from keras.layers import LeakyReLU
LeakyReLU = LeakyReLU(negative_slope=0.1)
import warnings
warnings.filterwarnings('ignore')
pd.set_option("display.max_columns", None)

## Data

In [4]:
# path to files
path = r'C:\Users\isava\OneDrive\Documents\CareerFoundry\MachineLearning\ClimateWins\02 Data\OriginalData'
# features filename
features = "Dataset-weather-prediction-dataset-processed.csv"
# labels filename
labels = "Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv"

In [5]:
df = pd.read_csv(os.path.join(path, features))
df

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_cloud_cover,GDANSK_humidity,GDANSK_precipitation,GDANSK_snow_depth,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_cloud_cover,ROMA_wind_speed,ROMA_humidity,ROMA_pressure,ROMA_sunshine,ROMA_temp_mean,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,8,0.91,0.00,0,0.8,-0.3,1.6,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.00,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,3,2.6,0.73,1.0152,7.1,7.8,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,3.8,0.76,1.0169,1.54,0.44,10.0,7.8,12.2,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,8,0.93,0.08,0,1.6,0.9,2.2,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.00,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,3,2.6,0.73,1.0152,7.1,12.2,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,3.8,0.76,1.0169,1.54,0.71,9.5,7.0,12.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.94,0.15,0,0.7,0.4,1.7,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.00,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,3,2.6,0.73,1.0152,7.1,10.2,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,3.8,0.76,1.0169,1.54,0.10,10.3,9.0,11.6,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,7,0.91,0.00,0,-0.1,-0.9,2.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.00,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,3,2.6,0.73,1.0152,7.1,10.8,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,3.8,0.76,1.0169,1.54,0.10,11.2,9.9,12.6,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,7,0.94,0.17,0,0.4,-1.7,1.5,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.00,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,3,2.6,0.73,1.0152,7.1,9.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3.8,0.76,1.0169,1.54,0.00,11.4,10.7,12.0,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,10,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,15.9,11.4,21.4,2,0.68,1.0278,1.57,0.18,5.7,18.2,12.1,24.4,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,3.0,0.84,1.0190,1.13,0.22,2.8,15.7,12.8,19.4,8,6.0,0.75,1.0214,1.13,0.20,0,6.4,17.8,13.6,21.4,6,0.70,0.12,0,11.5,8.0,15.0,5,0.87,1.0140,1.18,0.16,0,1.9,16.4,11.9,18.9,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,4,0.1,0.80,1.0289,1.35,0.37,5.9,14.7,12.1,21.1,8,3.8,0.67,1.0201,1.17,0.20,5.3,18.6,14.1,22.6,8,1.7,0.52,1.0204,1.89,0.12,5.3,20.0,16.2,23.9,2,0.76,1.37,0.26,0,9.7,14.3,8.3,22.2,8,1.1,0.98,1.0139,1.06,0.21,0,0.1,9.7,5.8,12.0,3,1.0,0.73,1.0152,7.1,15.4,2,5.7,0.84,1.0263,1.56,0.47,4.7,0.6,-1.4,2.6,5,1.0161,1.11,0.14,3.2,11.5,8.2,14.2,3.7,0.00,1.0174,1.54,0.18,19.9,14.2,25.7,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,20221028,10,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,16.7,14.3,21.9,0,0.68,1.0295,1.57,0.18,5.7,15.9,10.6,21.2,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,2.9,0.84,1.0177,1.13,0.22,3.5,16.0,10.3,20.5,7,5.2,0.71,1.0186,1.13,0.20,0,4.9,19.4,15.4,23.9,6,0.70,0.12,0,11.7,7.9,15.5,4,0.82,1.0152,1.18,0.16,0,4.2,15.8,12.7,21.8,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.1,0.82,1.0291,1.35,0.37,4.5,12.9,9.8,19.8,7,3.9,0.70,1.0190,1.17,0.20,5.0,18.9,15.8,23.5,8,2.2,0.51,1.0221,1.89,0.12,3.9,19.1,14.7,23.5,6,0.70,1.37,0.26,0,7.7,16.1,8.9,26.1,8,1.5,1.00,1.0107,1.06,0.21,0,0.0,10.9,8.8,11.7,3,1.2,0.73,1.0152,7.1,15.4,5,4.5,0.84,1.0263,1.56,0.47,4.7,2.3,0.6,4.0,5,1.0122,1.11,0.14,0.8,12.5,11.0,14.3,3.2,0.00,1.0189,1.54,0.18,20.3,16.5,24.2,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,20221029,10,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,16.7,13.1,22.4,2,0.68,1.0278,1.57,0.18,5.7,13.4,8.6,18.2,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,2.2,0.86,1.0174,1.13,0.22,3.3,15.8,9.3,21.1,8,4.4,0.73,1.0196,1.13,0.20,0,4.0,18.2,13.4,22.0,7,0.70,0.12,0,14.2,11.5,16.9,7,0.85,1.0138,1.18,0.16,0,4.2,16.5,11.2,17.0,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.1,0.81,1.0270,1.35,0.37,5.1,13.2,10.2,20.7,8,2.5,0.69,1.0183,1.17,0.20,3.2,18.2,13.7,24.3,8,1.9,0.46,1.0186,1.89,0.12,8.1,19.0,15.4,22.6,7,0.64,1.37,0.26,0,6.8,17.4,11.2,26.2,3,2.1,0.85,1.0082,1.06,0.21,0,6.8,9.7,7.7,14.2,3,1.5,0.73,1.0152,7.1,15.4,3,3.7,0.84,1.0263,1.56,0.47,4.7,3.3,2.1,4.5,5,1.0059,1.11,0.14,6.9,13.1,12.1,14.4,3.7,0.00,1.0172,1.54,0.18,20.6,16.7,24.5,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,20221030,10,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,15.4,11.6,21.1,1,0.68,1.0238,1.57,0.18,5.7,15.0,9.1,20.9,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,1.8,0.87,1.0174,1.13,0.22,6.0,14.4,10.3,20.2,7,3.9,0.73,1.0176,1.13,0.20,0,6.9,16.7,11.9,21.1,6,0.70,0.12,0,11.0,7.5,14.6,5,0.86,1.0147,1.18,0.16,0,0.6,15.2,13.4,17.5,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.0,0.77,1.0238,1.35,0.37,5.7,14.0,10.0,23.1,8,2.8,0.73,1.0181,1.17,0.20,6.8,16.3,12.8,21.4,5,1.1,0.66,1.0186,1.89,0.12,3.1,15.7,13.1,18.3,6,0.75,1.37,0.26,0,8.3,14.5,9.2,23.5,5,1.2,0.94,1.0150,1.06,0.21,0,2.9,5.9,2.1,8.1,3,1.2,0.73,1.0152,7.1,15.4,3,7.2,0.84,1.0263,1.56,0.47,4.7,3.4,2.7,4.1,5,1.0160,1.11,0.14,8.4,7.5,5.1,12.4,2.0,0.00,1.0187,1.54,0.18,15.9,12.4,19.4,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,20221031,10,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,13.5,9.9,19.2,4,0.68,1.0235,1.57,0.18,5.7,14.4,10.4,18.4,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,2.5,0.89,1.0156,1.13,0.22,0.7,12.8,6.7,16.2,8,3.0,0.78,1.0184,1.13,0.20,0,1.7,15.2,9.7,19.5,7,0.70,0.12,0,9.3,6.2,12.5,5,0.89,1.0107,1.18,0.16,0,3.7,13.7,9.8,17.6,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.0,0.77,1.0114,1.35,0.37,6.3,13.6,8.8,23.4,8,2.9,0.80,1.0160,1.17,0.20,3.0,15.3,11.0,19.4,8,1.7,0.82,1.0188,1.89,0.12,0.0,14.1,12.1,16.1,5,0.83,1.37,0.26,0,6.8,12.9,7.9,19.6,6,1.1,0.97,1.0148,1.06,0.21,0,1.9,9.2,7.5,13.3,3,1.5,0.73,1.0152,7.1,15.4,4,10.5,0.84,1.0263,1.56,0.47,4.7,1.7,0.7,2.7,5,1.0164,1.11,0.14,0.4,9.7,5.0,12.6,4.7,0.00,1.0143,1.54,0.18,16.8,12.1,21.5,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [6]:
df_labels = pd.read_csv(os.path.join(path, labels))
df_labels

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22946,20221028,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22947,20221029,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22948,20221030,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22949,20221031,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
# list of cities in features because we suspect that we have more than the labels dataframe has
cities_in_features = list(set([col.split("_")[0] for col in df.columns if col not in ["DATE", "MONTH"]])) # use set() to filter out duplicate names
cities_in_features

['KASSEL',
 'STOCKHOLM',
 'DEBILT',
 'HEATHROW',
 'MAASTRICHT',
 'DUSSELDORF',
 'MADRID',
 'MUNCHENB',
 'ROMA',
 'TOURS',
 'BELGRADE',
 'SONNBLICK',
 'BUDAPEST',
 'GDANSK',
 'LJUBLJANA',
 'VALENTIA',
 'BASEL',
 'OSLO']

In [8]:
len(cities_in_features)

18

In [9]:
# list of the cities in labels
cities_in_labels = [col.replace("_pleasant_weather", "") for col in df_labels.columns if col != "DATE"] # using replace instead of split here because every column has "_pleasant_weather" in it except DATE
cities_in_labels

['BASEL',
 'BELGRADE',
 'BUDAPEST',
 'DEBILT',
 'DUSSELDORF',
 'HEATHROW',
 'KASSEL',
 'LJUBLJANA',
 'MAASTRICHT',
 'MADRID',
 'MUNCHENB',
 'OSLO',
 'SONNBLICK',
 'STOCKHOLM',
 'VALENTIA']

In [10]:
len(cities_in_labels)

15

In [11]:
# create a list of columns to drop from features
cities_to_drop = [city for city in cities_in_features if city not in cities_in_labels]
columns_to_drop = [col for col in df.columns if col.split("_")[0] in cities_to_drop]
columns_to_drop

['GDANSK_cloud_cover',
 'GDANSK_humidity',
 'GDANSK_precipitation',
 'GDANSK_snow_depth',
 'GDANSK_temp_mean',
 'GDANSK_temp_min',
 'GDANSK_temp_max',
 'ROMA_cloud_cover',
 'ROMA_wind_speed',
 'ROMA_humidity',
 'ROMA_pressure',
 'ROMA_sunshine',
 'ROMA_temp_mean',
 'TOURS_wind_speed',
 'TOURS_humidity',
 'TOURS_pressure',
 'TOURS_global_radiation',
 'TOURS_precipitation',
 'TOURS_temp_mean',
 'TOURS_temp_min',
 'TOURS_temp_max']

In [12]:
df = df.drop(columns=columns_to_drop)
df

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.00,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.00,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.00,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.00,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.00,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,10,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,15.9,11.4,21.4,2,0.68,1.0278,1.57,0.18,5.7,18.2,12.1,24.4,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,3.0,0.84,1.0190,1.13,0.22,2.8,15.7,12.8,19.4,8,6.0,0.75,1.0214,1.13,0.20,0,6.4,17.8,13.6,21.4,5,0.87,1.0140,1.18,0.16,0,1.9,16.4,11.9,18.9,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,4,0.1,0.80,1.0289,1.35,0.37,5.9,14.7,12.1,21.1,8,3.8,0.67,1.0201,1.17,0.20,5.3,18.6,14.1,22.6,8,1.7,0.52,1.0204,1.89,0.12,5.3,20.0,16.2,23.9,2,0.76,1.37,0.26,0,9.7,14.3,8.3,22.2,8,1.1,0.98,1.0139,1.06,0.21,0,0.1,9.7,5.8,12.0,2,5.7,0.84,1.0263,1.56,0.47,4.7,0.6,-1.4,2.6,5,1.0161,1.11,0.14,3.2,11.5,8.2,14.2,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,20221028,10,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,16.7,14.3,21.9,0,0.68,1.0295,1.57,0.18,5.7,15.9,10.6,21.2,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,2.9,0.84,1.0177,1.13,0.22,3.5,16.0,10.3,20.5,7,5.2,0.71,1.0186,1.13,0.20,0,4.9,19.4,15.4,23.9,4,0.82,1.0152,1.18,0.16,0,4.2,15.8,12.7,21.8,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.1,0.82,1.0291,1.35,0.37,4.5,12.9,9.8,19.8,7,3.9,0.70,1.0190,1.17,0.20,5.0,18.9,15.8,23.5,8,2.2,0.51,1.0221,1.89,0.12,3.9,19.1,14.7,23.5,6,0.70,1.37,0.26,0,7.7,16.1,8.9,26.1,8,1.5,1.00,1.0107,1.06,0.21,0,0.0,10.9,8.8,11.7,5,4.5,0.84,1.0263,1.56,0.47,4.7,2.3,0.6,4.0,5,1.0122,1.11,0.14,0.8,12.5,11.0,14.3,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,20221029,10,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,16.7,13.1,22.4,2,0.68,1.0278,1.57,0.18,5.7,13.4,8.6,18.2,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,2.2,0.86,1.0174,1.13,0.22,3.3,15.8,9.3,21.1,8,4.4,0.73,1.0196,1.13,0.20,0,4.0,18.2,13.4,22.0,7,0.85,1.0138,1.18,0.16,0,4.2,16.5,11.2,17.0,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.1,0.81,1.0270,1.35,0.37,5.1,13.2,10.2,20.7,8,2.5,0.69,1.0183,1.17,0.20,3.2,18.2,13.7,24.3,8,1.9,0.46,1.0186,1.89,0.12,8.1,19.0,15.4,22.6,7,0.64,1.37,0.26,0,6.8,17.4,11.2,26.2,3,2.1,0.85,1.0082,1.06,0.21,0,6.8,9.7,7.7,14.2,3,3.7,0.84,1.0263,1.56,0.47,4.7,3.3,2.1,4.5,5,1.0059,1.11,0.14,6.9,13.1,12.1,14.4,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,20221030,10,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,15.4,11.6,21.1,1,0.68,1.0238,1.57,0.18,5.7,15.0,9.1,20.9,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,1.8,0.87,1.0174,1.13,0.22,6.0,14.4,10.3,20.2,7,3.9,0.73,1.0176,1.13,0.20,0,6.9,16.7,11.9,21.1,5,0.86,1.0147,1.18,0.16,0,0.6,15.2,13.4,17.5,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.0,0.77,1.0238,1.35,0.37,5.7,14.0,10.0,23.1,8,2.8,0.73,1.0181,1.17,0.20,6.8,16.3,12.8,21.4,5,1.1,0.66,1.0186,1.89,0.12,3.1,15.7,13.1,18.3,6,0.75,1.37,0.26,0,8.3,14.5,9.2,23.5,5,1.2,0.94,1.0150,1.06,0.21,0,2.9,5.9,2.1,8.1,3,7.2,0.84,1.0263,1.56,0.47,4.7,3.4,2.7,4.1,5,1.0160,1.11,0.14,8.4,7.5,5.1,12.4,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,20221031,10,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,13.5,9.9,19.2,4,0.68,1.0235,1.57,0.18,5.7,14.4,10.4,18.4,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,2.5,0.89,1.0156,1.13,0.22,0.7,12.8,6.7,16.2,8,3.0,0.78,1.0184,1.13,0.20,0,1.7,15.2,9.7,19.5,5,0.89,1.0107,1.18,0.16,0,3.7,13.7,9.8,17.6,2.4,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.0,0.77,1.0114,1.35,0.37,6.3,13.6,8.8,23.4,8,2.9,0.80,1.0160,1.17,0.20,3.0,15.3,11.0,19.4,8,1.7,0.82,1.0188,1.89,0.12,0.0,14.1,12.1,16.1,5,0.83,1.37,0.26,0,6.8,12.9,7.9,19.6,6,1.1,0.97,1.0148,1.06,0.21,0,1.9,9.2,7.5,13.3,4,10.5,0.84,1.0263,1.56,0.47,4.7,1.7,0.7,2.7,5,1.0164,1.11,0.14,0.4,9.7,5.0,12.6,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [13]:
# create list of weather attributes to see which stations are missing them
attributes = list(set([col.split("_", maxsplit=1)[1] for col in df.columns if col not in ["DATE", "MONTH"]])) # use set to filter out duplicate attributes
attributes

['humidity',
 'precipitation',
 'global_radiation',
 'temp_max',
 'snow_depth',
 'temp_min',
 'wind_speed',
 'sunshine',
 'temp_mean',
 'pressure',
 'cloud_cover']

In [14]:
for attrib in attributes:
    attrib_count = 0
    for col in df.columns:
        if attrib in col:
            attrib_count +=1

    print(attrib, attrib_count)

humidity 14
precipitation 15
global_radiation 15
temp_max 15
snow_depth 6
temp_min 15
wind_speed 9
sunshine 15
temp_mean 15
pressure 14
cloud_cover 14

In [15]:
# looks like snow_depth and wind_speed are missing from several stations so we'll drop them
cols_to_drop = [col for col in df.columns if "wind_speed" in col or "snow_depth" in col]
cols_to_drop

['BASEL_wind_speed',
 'BASEL_snow_depth',
 'DEBILT_wind_speed',
 'DUSSELDORF_wind_speed',
 'DUSSELDORF_snow_depth',
 'HEATHROW_snow_depth',
 'KASSEL_wind_speed',
 'LJUBLJANA_wind_speed',
 'MAASTRICHT_wind_speed',
 'MADRID_wind_speed',
 'MUNCHENB_snow_depth',
 'OSLO_wind_speed',
 'OSLO_snow_depth',
 'SONNBLICK_wind_speed',
 'VALENTIA_snow_depth']

In [16]:
df = df.drop(columns=cols_to_drop)
df

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.0180,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.00,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.0180,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.00,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.0180,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.00,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.0180,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.00,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.0180,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.00,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,10,1,0.79,1.0248,1.34,0.22,7.7,15.9,11.4,21.4,2,0.68,1.0278,1.57,0.18,5.7,18.2,12.1,24.4,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,0.84,1.0190,1.13,0.22,2.8,15.7,12.8,19.4,8,0.75,1.0214,1.13,0.20,6.4,17.8,13.6,21.4,5,0.87,1.0140,1.18,0.16,1.9,16.4,11.9,18.9,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,4,0.80,1.0289,1.35,0.37,5.9,14.7,12.1,21.1,8,0.67,1.0201,1.17,0.20,5.3,18.6,14.1,22.6,8,0.52,1.0204,1.89,0.12,5.3,20.0,16.2,23.9,2,0.76,1.37,0.26,9.7,14.3,8.3,22.2,8,0.98,1.0139,1.06,0.21,0.1,9.7,5.8,12.0,2,0.84,1.0263,1.56,0.47,4.7,0.6,-1.4,2.6,5,1.0161,1.11,0.14,3.2,11.5,8.2,14.2,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22946,20221028,10,6,0.77,1.0244,1.34,0.22,5.4,16.7,14.3,21.9,0,0.68,1.0295,1.57,0.18,5.7,15.9,10.6,21.2,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,0.84,1.0177,1.13,0.22,3.5,16.0,10.3,20.5,7,0.71,1.0186,1.13,0.20,4.9,19.4,15.4,23.9,4,0.82,1.0152,1.18,0.16,4.2,15.8,12.7,21.8,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.82,1.0291,1.35,0.37,4.5,12.9,9.8,19.8,7,0.70,1.0190,1.17,0.20,5.0,18.9,15.8,23.5,8,0.51,1.0221,1.89,0.12,3.9,19.1,14.7,23.5,6,0.70,1.37,0.26,7.7,16.1,8.9,26.1,8,1.00,1.0107,1.06,0.21,0.0,10.9,8.8,11.7,5,0.84,1.0263,1.56,0.47,4.7,2.3,0.6,4.0,5,1.0122,1.11,0.14,0.8,12.5,11.0,14.3,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22947,20221029,10,4,0.76,1.0227,1.34,0.22,6.1,16.7,13.1,22.4,2,0.68,1.0278,1.57,0.18,5.7,13.4,8.6,18.2,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,0.86,1.0174,1.13,0.22,3.3,15.8,9.3,21.1,8,0.73,1.0196,1.13,0.20,4.0,18.2,13.4,22.0,7,0.85,1.0138,1.18,0.16,4.2,16.5,11.2,17.0,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.81,1.0270,1.35,0.37,5.1,13.2,10.2,20.7,8,0.69,1.0183,1.17,0.20,3.2,18.2,13.7,24.3,8,0.46,1.0186,1.89,0.12,8.1,19.0,15.4,22.6,7,0.64,1.37,0.26,6.8,17.4,11.2,26.2,3,0.85,1.0082,1.06,0.21,6.8,9.7,7.7,14.2,3,0.84,1.0263,1.56,0.47,4.7,3.3,2.1,4.5,5,1.0059,1.11,0.14,6.9,13.1,12.1,14.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22948,20221030,10,5,0.80,1.0212,1.34,0.22,5.8,15.4,11.6,21.1,1,0.68,1.0238,1.57,0.18,5.7,15.0,9.1,20.9,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,0.87,1.0174,1.13,0.22,6.0,14.4,10.3,20.2,7,0.73,1.0176,1.13,0.20,6.9,16.7,11.9,21.1,5,0.86,1.0147,1.18,0.16,0.6,15.2,13.4,17.5,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.77,1.0238,1.35,0.37,5.7,14.0,10.0,23.1,8,0.73,1.0181,1.17,0.20,6.8,16.3,12.8,21.4,5,0.66,1.0186,1.89,0.12,3.1,15.7,13.1,18.3,6,0.75,1.37,0.26,8.3,14.5,9.2,23.5,5,0.94,1.0150,1.06,0.21,2.9,5.9,2.1,8.1,3,0.84,1.0263,1.56,0.47,4.7,3.4,2.7,4.1,5,1.0160,1.11,0.14,8.4,7.5,5.1,12.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22949,20221031,10,5,0.84,1.0193,1.34,0.22,3.2,13.5,9.9,19.2,4,0.68,1.0235,1.57,0.18,5.7,14.4,10.4,18.4,4,0.67,1.017,1.41,0.14,5.4,11.7,7.9,16.2,8,0.89,1.0156,1.13,0.22,0.7,12.8,6.7,16.2,8,0.78,1.0184,1.13,0.20,1.7,15.2,9.7,19.5,5,0.89,1.0107,1.18,0.16,3.7,13.7,9.8,17.6,0.77,1.0161,1.14,0.19,4.0,9.1,5.4,13.1,3,0.77,1.0114,1.35,0.37,6.3,13.6,8.8,23.4,8,0.80,1.0160,1.17,0.20,3.0,15.3,11.0,19.4,8,0.82,1.0188,1.89,0.12,0.0,14.1,12.1,16.1,5,0.83,1.37,0.26,6.8,12.9,7.9,19.6,6,0.97,1.0148,1.06,0.21,1.9,9.2,7.5,13.3,4,0.84,1.0263,1.56,0.47,4.7,1.7,0.7,2.7,5,1.0164,1.11,0.14,0.4,9.7,5.0,12.6,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5

In [17]:
attributes.remove("snow_depth")
attributes.remove("wind_speed")

In [18]:
# what attributes are missing?  we're looking for three of them and we can find them in the counts above
missing_attributes = ["humidity", "cloud_cover", "pressure"]
for city in cities_in_labels:
    relevant_columns = [col.split("_", maxsplit=1)[1] for col in df.columns if city in col]
    for attrib in attributes:
        if attrib not in relevant_columns:
            print(city, attrib)

KASSEL cloud_cover
MUNCHENB pressure
STOCKHOLM humidity

In [19]:
KASSEL_cloud_cover = df["LJUBLJANA_cloud_cover"]
MUNCHENB_pressure = df["SONNBLICK_pressure"]
STOCKHOLM_humidity = df["OSLO_humidity"]

In [20]:
for i, col in enumerate(df.columns): # run this before inserting columns and after every column insertion to ensure correct indexing
    print(i, col)

0 DATE
1 MONTH
2 BASEL_cloud_cover
3 BASEL_humidity
4 BASEL_pressure
5 BASEL_global_radiation
6 BASEL_precipitation
7 BASEL_sunshine
8 BASEL_temp_mean
9 BASEL_temp_min
10 BASEL_temp_max
11 BELGRADE_cloud_cover
12 BELGRADE_humidity
13 BELGRADE_pressure
14 BELGRADE_global_radiation
15 BELGRADE_precipitation
16 BELGRADE_sunshine
17 BELGRADE_temp_mean
18 BELGRADE_temp_min
19 BELGRADE_temp_max
20 BUDAPEST_cloud_cover
21 BUDAPEST_humidity
22 BUDAPEST_pressure
23 BUDAPEST_global_radiation
24 BUDAPEST_precipitation
25 BUDAPEST_sunshine
26 BUDAPEST_temp_mean
27 BUDAPEST_temp_min
28 BUDAPEST_temp_max
29 DEBILT_cloud_cover
30 DEBILT_humidity
31 DEBILT_pressure
32 DEBILT_global_radiation
33 DEBILT_precipitation
34 DEBILT_sunshine
35 DEBILT_temp_mean
36 DEBILT_temp_min
37 DEBILT_temp_max
38 DUSSELDORF_cloud_cover
39 DUSSELDORF_humidity
40 DUSSELDORF_pressure
41 DUSSELDORF_global_radiation
42 DUSSELDORF_precipitation
43 DUSSELDORF_sunshine
44 DUSSELDORF_temp_mean
45 DUSSELDORF_temp_min
46 DUSSELDORF_temp_max
47 HEATHROW_cloud_cover
48 HEATHROW_humidity
49 HEATHROW_pressure
50 HEATHROW_global_radiation
51 HEATHROW_precipitation
52 HEATHROW_sunshine
53 HEATHROW_temp_mean
54 HEATHROW_temp_min
55 HEATHROW_temp_max
56 KASSEL_humidity
57 KASSEL_pressure
58 KASSEL_global_radiation
59 KASSEL_precipitation
60 KASSEL_sunshine
61 KASSEL_temp_mean
62 KASSEL_temp_min
63 KASSEL_temp_max
64 LJUBLJANA_cloud_cover
65 LJUBLJANA_humidity
66 LJUBLJANA_pressure
67 LJUBLJANA_global_radiation
68 LJUBLJANA_precipitation
69 LJUBLJANA_sunshine
70 LJUBLJANA_temp_mean
71 LJUBLJANA_temp_min
72 LJUBLJANA_temp_max
73 MAASTRICHT_cloud_cover
74 MAASTRICHT_humidity
75 MAASTRICHT_pressure
76 MAASTRICHT_global_radiation
77 MAASTRICHT_precipitation
78 MAASTRICHT_sunshine
79 MAASTRICHT_temp_mean
80 MAASTRICHT_temp_min
81 MAASTRICHT_temp_max
82 MADRID_cloud_cover
83 MADRID_humidity
84 MADRID_pressure
85 MADRID_global_radiation
86 MADRID_precipitation
87 MADRID_sunshine
88 MADRID_temp_mean
89 MADRID_temp_min
90 MADRID_temp_max
91 MUNCHENB_cloud_cover
92 MUNCHENB_humidity
93 MUNCHENB_global_radiation
94 MUNCHENB_precipitation
95 MUNCHENB_sunshine
96 MUNCHENB_temp_mean
97 MUNCHENB_temp_min
98 MUNCHENB_temp_max
99 OSLO_cloud_cover
100 OSLO_humidity
101 OSLO_pressure
102 OSLO_global_radiation
103 OSLO_precipitation
104 OSLO_sunshine
105 OSLO_temp_mean
106 OSLO_temp_min
107 OSLO_temp_max
108 SONNBLICK_cloud_cover
109 SONNBLICK_humidity
110 SONNBLICK_pressure
111 SONNBLICK_global_radiation
112 SONNBLICK_precipitation
113 SONNBLICK_sunshine
114 SONNBLICK_temp_mean
115 SONNBLICK_temp_min
116 SONNBLICK_temp_max
117 STOCKHOLM_cloud_cover
118 STOCKHOLM_pressure
119 STOCKHOLM_global_radiation
120 STOCKHOLM_precipitation
121 STOCKHOLM_sunshine
122 STOCKHOLM_temp_mean
123 STOCKHOLM_temp_min
124 STOCKHOLM_temp_max
125 VALENTIA_cloud_cover
126 VALENTIA_humidity
127 VALENTIA_pressure
128 VALENTIA_global_radiation
129 VALENTIA_precipitation
130 VALENTIA_sunshine
131 VALENTIA_temp_mean
132 VALENTIA_temp_min
133 VALENTIA_temp_max

In [21]:
df.insert(56, "KASSEL_cloud_cover", KASSEL_cloud_cover) #Insert to keep the same order.

In [22]:
df.insert(94, "MUNCHENB_pressure", MUNCHENB_pressure)

In [23]:
df.insert(120, "STOCKHOLM_humidity", STOCKHOLM_humidity)

In [24]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.0304,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,6,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.0292,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,8,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.0320,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,6,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.0443,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.0430,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [25]:
df.to_csv(os.path.join(path, 'Dataset-weather-prediction-dataset-cleaned.csv'))

## Sampling

In [27]:
cutoff_date = 20100101 # split the data manually to preserve time series aspect (not fully necessary)
X_train = df.loc[df["DATE"] <= cutoff_date]
X_test = df.loc[df["DATE"] > cutoff_date]
y_train = df_labels.loc[df_labels["DATE"] <= cutoff_date]
y_test = df_labels.loc[df_labels["DATE"] > cutoff_date]

In [28]:
len(X_train) + len(X_test)

22950

In [29]:
X_train = X_train.drop(columns=["DATE", "MONTH"])
X_test = X_test.drop(columns=["DATE", "MONTH"])
y_train = y_train.drop(columns=["DATE"])
y_test = y_test.drop(columns=["DATE"])

In [30]:
# scale data here to prevent leakage from distribution of test data into train data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) # always transform the test data with the fitted object from the training data, never create a new scaling object

In [31]:
X_train = X_train.reshape(-1, 15, 9) # we want each data point to be 15 rows, 9 columns and -1 for however many data points this produces (should be length of X_train)
X_train.shape

(18264, 15, 9)

In [32]:
X_test = X_test.reshape(-1, 15, 9)
X_test.shape

(4686, 15, 9)

In [33]:
len(X_train[0][0])

9

In [34]:
y_train

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18260,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18261,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18262,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18263,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## CNN

A CNN model was chosen due to the shape of the data and the wrangling needed to get it into a Sparse MultiClass problem. Although an RNN with the use of temporal data could be interesting as well.

In [36]:
y_train

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18260,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18261,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18262,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18263,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [37]:
# build the model
epochs = 50
batch_size = 64
n_hidden = 100

dim1 = len(X_train[0])
dim2 = len(X_train[0][0])
n_classes = 15 # 15 classes because we have 15 columns of labels

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(dim1, dim2))) # dim1 and dim2 are basically the number of rows and columns of one data point
model.add(Dense(n_hidden, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='sigmoid')) # sigmoid so that the pr3ediction probabilities for each row don't have to sum to 1

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["binary_accuracy"]) # binary crossentropy because it's applied to each output node, so each of the 15 stations preds are independent
# also binary accuracy otherwise it won't be calculated correctly

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2, validation_data=(X_test, y_test))

Epoch 1/50
286/286 - 6s - 19ms/step - binary_accuracy: 0.8941 - loss: 0.2328 - val_binary_accuracy: 0.8974 - val_loss: 0.3066
Epoch 2/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9315 - loss: 0.1588 - val_binary_accuracy: 0.9182 - val_loss: 0.2581
Epoch 3/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9413 - loss: 0.1376 - val_binary_accuracy: 0.9272 - val_loss: 0.2321
Epoch 4/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9474 - loss: 0.1242 - val_binary_accuracy: 0.9358 - val_loss: 0.1837
Epoch 5/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9528 - loss: 0.1124 - val_binary_accuracy: 0.9409 - val_loss: 0.1813
Epoch 6/50
286/286 - 3s - 9ms/step - binary_accuracy: 0.9571 - loss: 0.1036 - val_binary_accuracy: 0.9476 - val_loss: 0.1474
Epoch 7/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9605 - loss: 0.0961 - val_binary_accuracy: 0.9467 - val_loss: 0.1813
Epoch 8/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9634 - loss: 0.0899 - val_binary_accuracy: 0.9491 - val_loss: 0.1451
Epoch 9/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9663 - loss: 0.0839 - val_binary_accuracy: 0.9542 - val_loss: 0.1268
Epoch 10/50
286/286 - 3s - 10ms/step - binary_accuracy: 0.9687 - loss: 0.0783 - val_binary_accuracy: 0.9554 - val_loss: 0.1274
Epoch 11/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9709 - loss: 0.0741 - val_binary_accuracy: 0.9580 - val_loss: 0.1275
Epoch 12/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9723 - loss: 0.0700 - val_binary_accuracy: 0.9575 - val_loss: 0.1612
Epoch 13/50
286/286 - 3s - 9ms/step - binary_accuracy: 0.9742 - loss: 0.0661 - val_binary_accuracy: 0.9613 - val_loss: 0.1221
Epoch 14/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9754 - loss: 0.0633 - val_binary_accuracy: 0.9563 - val_loss: 0.1399
Epoch 15/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9770 - loss: 0.0597 - val_binary_accuracy: 0.9618 - val_loss: 0.1272
Epoch 16/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9779 - loss: 0.0574 - val_binary_accuracy: 0.9634 - val_loss: 0.1388
Epoch 17/50
286/286 - 3s - 9ms/step - binary_accuracy: 0.9789 - loss: 0.0550 - val_binary_accuracy: 0.9654 - val_loss: 0.1521
Epoch 18/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9800 - loss: 0.0518 - val_binary_accuracy: 0.9664 - val_loss: 0.1152
Epoch 19/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9808 - loss: 0.0504 - val_binary_accuracy: 0.9673 - val_loss: 0.1406
Epoch 20/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9819 - loss: 0.0480 - val_binary_accuracy: 0.9680 - val_loss: 0.1497
Epoch 21/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9826 - loss: 0.0462 - val_binary_accuracy: 0.9676 - val_loss: 0.1231
Epoch 22/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9832 - loss: 0.0448 - val_binary_accuracy: 0.9689 - val_loss: 0.1348
Epoch 23/50
286/286 - 3s - 9ms/step - binary_accuracy: 0.9840 - loss: 0.0429 - val_binary_accuracy: 0.9680 - val_loss: 0.1435
Epoch 24/50
286/286 - 2s - 7ms/step - binary_accuracy: 0.9846 - loss: 0.0410 - val_binary_accuracy: 0.9666 - val_loss: 0.1488
Epoch 25/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9848 - loss: 0.0401 - val_binary_accuracy: 0.9694 - val_loss: 0.1348
Epoch 26/50
286/286 - 2s - 7ms/step - binary_accuracy: 0.9856 - loss: 0.0383 - val_binary_accuracy: 0.9675 - val_loss: 0.1555
Epoch 27/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9861 - loss: 0.0372 - val_binary_accuracy: 0.9707 - val_loss: 0.1323
Epoch 28/50
286/286 - 3s - 10ms/step - binary_accuracy: 0.9866 - loss: 0.0360 - val_binary_accuracy: 0.9713 - val_loss: 0.1891
Epoch 29/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9866 - loss: 0.0355 - val_binary_accuracy: 0.9687 - val_loss: 0.1687
Epoch 30/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9875 - loss: 0.0342 - val_binary_accuracy: 0.9707 - val_loss: 0.1631
Epoch 31/50
286/286 - 3s - 9ms/step - binary_accuracy: 0.9875 - loss: 0.0333 - val_binary_accuracy: 0.9702 - val_loss: 0.1519
Epoch 32/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9885 - loss: 0.0316 - val_binary_accuracy: 0.9692 - val_loss: 0.1837
Epoch 33/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9888 - loss: 0.0308 - val_binary_accuracy: 0.9709 - val_loss: 0.1786
Epoch 34/50
286/286 - 3s - 11ms/step - binary_accuracy: 0.9887 - loss: 0.0307 - val_binary_accuracy: 0.9712 - val_loss: 0.2142
Epoch 35/50
286/286 - 5s - 18ms/step - binary_accuracy: 0.9896 - loss: 0.0286 - val_binary_accuracy: 0.9706 - val_loss: 0.2017
Epoch 36/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9898 - loss: 0.0279 - val_binary_accuracy: 0.9727 - val_loss: 0.2087
Epoch 37/50
286/286 - 2s - 9ms/step - binary_accuracy: 0.9900 - loss: 0.0272 - val_binary_accuracy: 0.9703 - val_loss: 0.2048
Epoch 38/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9903 - loss: 0.0269 - val_binary_accuracy: 0.9712 - val_loss: 0.2006
Epoch 39/50
286/286 - 3s - 10ms/step - binary_accuracy: 0.9905 - loss: 0.0262 - val_binary_accuracy: 0.9701 - val_loss: 0.2013
Epoch 40/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9906 - loss: 0.0257 - val_binary_accuracy: 0.9701 - val_loss: 0.2129
Epoch 41/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9909 - loss: 0.0249 - val_binary_accuracy: 0.9742 - val_loss: 0.2444
Epoch 42/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9910 - loss: 0.0244 - val_binary_accuracy: 0.9712 - val_loss: 0.2429
Epoch 43/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9914 - loss: 0.0237 - val_binary_accuracy: 0.9721 - val_loss: 0.2524
Epoch 44/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9916 - loss: 0.0228 - val_binary_accuracy: 0.9738 - val_loss: 0.2527
Epoch 45/50
286/286 - 2s - 8ms/step - binary_accuracy: 0.9917 - loss: 0.0228 - val_binary_accuracy: 0.9712 - val_loss: 0.2553
Epoch 46/50
286/286 - 3s - 9ms/step - binary_accuracy: 0.9925 - loss: 0.0212 - val_binary_accuracy: 0.9727 - val_loss: 0.2503
Epoch 47/50
286/286 - 5s - 17ms/step - binary_accuracy: 0.9921 - loss: 0.0215 - val_binary_accuracy: 0.9729 - val_loss: 0.2869
Epoch 48/50
286/286 - 2s - 9ms/step - binary_accuracy: 0.9928 - loss: 0.0205 - val_binary_accuracy: 0.9718 - val_loss: 0.2573
Epoch 49/50
286/286 - 3s - 10ms/step - binary_accuracy: 0.9929 - loss: 0.0202 - val_binary_accuracy: 0.9691 - val_loss: 0.3188
Epoch 50/50
286/286 - 3s - 11ms/step - binary_accuracy: 0.9929 - loss: 0.0198 - val_binary_accuracy: 0.9720 - val_loss: 0.2563

The model is converging very well with an increase in accuracy and loss decrease.

In [39]:
preds = model.predict(X_test).round()

147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

In [40]:
preds[1000:1050] # notice how any given row can have more than one "1" in it, we're not predicting which station has a "1", it wouldn't make sense

array([[1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [41]:
locations = list({x.split("_")[0] for x in df.columns if x not in ["MONTH", "DATE"]})
locations

['KASSEL',
 'STOCKHOLM',
 'DEBILT',
 'HEATHROW',
 'MAASTRICHT',
 'DUSSELDORF',
 'MADRID',
 'MUNCHENB',
 'BELGRADE',
 'SONNBLICK',
 'BUDAPEST',
 'LJUBLJANA',
 'VALENTIA',
 'BASEL',
 'OSLO']

In [42]:
print(metrics.classification_report(y_test.values, preds, zero_division = np.nan, target_names = locations))

              precision    recall  f1-score   support

      KASSEL       0.99      0.81      0.89      1299
   STOCKHOLM       0.97      0.95      0.96      1755
      DEBILT       0.96      0.96      0.96      1459
    HEATHROW       0.95      0.93      0.94      1044
  MAASTRICHT       0.97      0.92      0.94      1135
  DUSSELDORF       0.96      0.89      0.93      1140
      MADRID       0.96      0.99      0.97       308
    MUNCHENB       0.93      0.93      0.93      1425
    BELGRADE       0.97      0.96      0.97      1156
   SONNBLICK       0.96      0.92      0.94      2256
    BUDAPEST       0.92      0.99      0.95      1129
   LJUBLJANA       0.85      0.88      0.87       738
    VALENTIA        nan       nan       nan         0
       BASEL       0.93      0.89      0.91       941
        OSLO        nan       nan       nan         0

   micro avg       0.95      0.92      0.94     15785
   macro avg       0.95      0.92      0.94     15785
weighted avg       0.95      0.92      0.94     15785
 samples avg       0.93      0.90      0.88     15785

In [43]:
y_test['MAASTRICHT_pleasant_weather'].sum

<bound method Series.sum of 18264    0
18265    0
18266    0
18267    0
18268    0
        ..
22945    0
22946    0
22947    0
22948    0
22949    0
Name: MAASTRICHT_pleasant_weather, Length: 4686, dtype: int64>

In [44]:
preds[12] #All 0s - > NAN f1 score for MAASTRICHT; also all 0s in test values/

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [45]:
y_test.shape

(4686, 15)

Very good F1 scores for each station. MAASTRICHT is nan due to unpleasant weather predictions and test data also unpleasant weather.

## Parameter Optimization

In [48]:
X_train.shape

(18264, 15, 9)

In [49]:
y_train.shape

(18264, 15)

In [50]:
#y_train = np.argmax(y_train, axis = 1)
#print(y_train.shape)
#y_train

In [52]:
#Set up        
dim1 = len(X_train[0])
dim2 = len(X_train[0][0])
n_classes = 15 # 15 classes because we have 15 columns of labels
score_acc = make_scorer(accuracy_score)

In [146]:
#Modified to assist in this completing faster (the original took over 8 hours and crashed my computer
def bay_area(neurons, activation, kernel, optimizer, batch_size, epochs,
              layers1, layers2, normalization, dropout, dropout_rate): 
    optimizerL = ['SGD', 'Adam', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','SGD']
    #optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
                 #'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
                 #'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
                 #'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
    activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
                   'elu', 'exponential', LeakyReLU,'relu']
    
    neurons = round(neurons)
    kernel = round(kernel)
    activation = activationL[round(activation)]  #optimizerD[optimizerL[round(optimizer)]]
    optimizer = optimizerL[round(optimizer)]
    batch_size = round(batch_size)
    
    epochs = round(epochs)
    layers1 = round(layers1)
    layers2 = round(layers2)
    
    def cnn_model():
        model = Sequential()
        model.add(Conv1D(neurons, kernel_size=kernel,activation=activation, input_shape=(dim1, dim2)))
        #model.add(Conv1D(32, kernel_size=1,activation='relu', input_shape=(timesteps, input_dim)))
        
        if normalization > 0.5:
            model.add(BatchNormalization())
        for i in range(layers1):
            model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
        if dropout > 0.5:
            model.add(Dropout(dropout_rate, seed=123))
        for i in range(layers2):
            model.add(Dense(neurons, activation=activation))
        model.add(MaxPooling1D())
        model.add(Flatten())
        model.add(Dense(n_classes, activation='sigmoid')) # sigmoid so that the pr3ediction probabilities for each row don't have to sum to 1
        #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=["binary_accuracy"]) # binary crossentropy because it's applied to each output node, so each of the 15 stations preds are independent
        # also binary accuracy otherwise it won't be calculated correctly
      
        #model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        return model
    es = EarlyStopping(monitor='binary_accuracy', mode='max', verbose=2, patience=20)
    nn = KerasClassifier(build_fn=cnn_model, epochs=epochs, batch_size=batch_size, verbose=2)
    kfold = KFold(n_splits=3, shuffle=True, random_state=123) #dropped to 3 folds to save memory/time
    score = cross_val_score(nn, X_train, y_train, scoring='f1_micro', cv=kfold, params={'callbacks':[es]}).mean()
    return score





#model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2, validation_data=(X_test, y_test))

In [150]:
start = time.time()
params ={
    'neurons': (10, 100), #save memory
    'kernel': (1, 3),
    'activation':(0, 9), #9
    'optimizer':(0,7), #7
    #'learning_rate':(0.01, 1),
    'batch_size': (15, 64), #save memory
    'epochs':(15, 50), #save memory
    'layers1':(1,3),
    'layers2':(1,3),
    'normalization':(0,1),
    'dropout':(0,1),
    'dropout_rate':(0,0.3)
}
# Run Bayesian Optimization
nn_opt = BayesianOptimization(bay_area, params, random_state=42)
nn_opt.maximize(init_points=10, n_iter=5) #25 #save time
print('Search took %s minutes' % ((time.time() - start)/60))

|   iter    |  target   |  neurons  |  kernel   | activa... | optimizer | batch_... |  epochs   |  layers1  |  layers2  | normal... |  dropout  | dropou... |
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Epoch 1/20
530/530 - 9s - 18ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 2/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 3/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 4/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 5/20
530/530 - 5s - 10ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 6/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 7/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 8/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 9/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 10/20
530/530 - 5s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 11/20
530/530 - 6s - 11ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 12/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 13/20
530/530 - 5s - 10ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 14/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 15/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 16/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 17/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 18/20
530/530 - 5s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 19/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 20/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7893 - loss: nan
265/265 - 2s - 6ms/step
Epoch 1/20
530/530 - 9s - 17ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 2/20
530/530 - 5s - 10ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 3/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 4/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 5/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 6/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 7/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 8/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 9/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 10/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 11/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 12/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 13/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 14/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 15/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 16/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 17/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 18/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 19/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7881 - loss: nan
Epoch 20/20
530/530 - 3s - 6ms/step - binary_accuracy: 0.7881 - loss: nan
265/265 - 1s - 5ms/step
Epoch 1/20
530/530 - 7s - 12ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 2/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 3/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 4/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 5/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 6/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 7/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 8/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 9/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 10/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 11/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 12/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 13/20
530/530 - 4s - 8ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 14/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 15/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 16/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 17/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 18/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 19/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
Epoch 20/20
530/530 - 4s - 7ms/step - binary_accuracy: 0.7850 - loss: nan
265/265 - 1s - 6ms/step
| 1         | 0.3505723 | 43.708610 | 2.9014286 | 6.5879454 | 4.1906093 | 22.644913 | 20.459808 | 1.1161672 | 2.7323522 | 0.6011150 | 0.7080725 | 0.0061753 |
Epoch 1/26
508/508 - 12s - 24ms/step - binary_accuracy: 0.8842 - loss: 0.2517
Epoch 2/26
508/508 - 11s - 22ms/step - binary_accuracy: 0.9164 - loss: 0.1876
Epoch 3/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9264 - loss: 0.1688
Epoch 4/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9341 - loss: 0.1527
Epoch 5/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9405 - loss: 0.1402
Epoch 6/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9459 - loss: 0.1279
Epoch 7/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9508 - loss: 0.1175
Epoch 8/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9553 - loss: 0.1095
Epoch 9/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9584 - loss: 0.1011
Epoch 10/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9608 - loss: 0.0953
Epoch 11/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9639 - loss: 0.0886
Epoch 12/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9656 - loss: 0.0845
Epoch 13/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9675 - loss: 0.0810
Epoch 14/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9681 - loss: 0.0790
Epoch 15/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9703 - loss: 0.0737
Epoch 16/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9702 - loss: 0.0731
Epoch 17/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9716 - loss: 0.0704
Epoch 18/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9724 - loss: 0.0682
Epoch 19/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9733 - loss: 0.0670
Epoch 20/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9739 - loss: 0.0648
Epoch 21/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9737 - loss: 0.0661
Epoch 22/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9753 - loss: 0.0622
Epoch 23/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9752 - loss: 0.0611
Epoch 24/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9759 - loss: 0.0598
Epoch 25/26
508/508 - 10s - 20ms/step - binary_accuracy: 0.9764 - loss: 0.0591
Epoch 26/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9770 - loss: 0.0569
254/254 - 2s - 7ms/step
Epoch 1/26
508/508 - 13s - 25ms/step - binary_accuracy: 0.8872 - loss: 0.2461
Epoch 2/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9142 - loss: 0.1921
Epoch 3/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9216 - loss: 0.1783
Epoch 4/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9289 - loss: 0.1644
Epoch 5/26
508/508 - 6s - 13ms/step - binary_accuracy: 0.9359 - loss: 0.1490
Epoch 6/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9415 - loss: 0.1380
Epoch 7/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9469 - loss: 0.1268
Epoch 8/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9515 - loss: 0.1164
Epoch 9/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9564 - loss: 0.1063
Epoch 10/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9581 - loss: 0.1024
Epoch 11/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9617 - loss: 0.0947
Epoch 12/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9635 - loss: 0.0899
Epoch 13/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9655 - loss: 0.0854
Epoch 14/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9670 - loss: 0.0820
Epoch 15/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9683 - loss: 0.0779
Epoch 16/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9694 - loss: 0.0758
Epoch 17/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9708 - loss: 0.0728
Epoch 18/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9719 - loss: 0.0703
Epoch 19/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9727 - loss: 0.0680
Epoch 20/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9734 - loss: 0.0655
Epoch 21/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9745 - loss: 0.0635
Epoch 22/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9760 - loss: 0.0610
Epoch 23/26
508/508 - 10s - 20ms/step - binary_accuracy: 0.9762 - loss: 0.0600
Epoch 24/26
508/508 - 5s - 11ms/step - binary_accuracy: 0.9760 - loss: 0.0594
Epoch 25/26
508/508 - 7s - 13ms/step - binary_accuracy: 0.9773 - loss: 0.0566
Epoch 26/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9776 - loss: 0.0563
254/254 - 2s - 7ms/step
Epoch 1/26
508/508 - 10s - 19ms/step - binary_accuracy: 0.8843 - loss: 0.2515
Epoch 2/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9144 - loss: 0.1920
Epoch 3/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9218 - loss: 0.1784
Epoch 4/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9278 - loss: 0.1657
Epoch 5/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9364 - loss: 0.1492
Epoch 6/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9428 - loss: 0.1348
Epoch 7/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9483 - loss: 0.1235
Epoch 8/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9525 - loss: 0.1143
Epoch 9/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9564 - loss: 0.1055
Epoch 10/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9592 - loss: 0.0982
Epoch 11/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9613 - loss: 0.0938
Epoch 12/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9636 - loss: 0.0891
Epoch 13/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9655 - loss: 0.0844
Epoch 14/26
508/508 - 6s - 12ms/step - binary_accuracy: 0.9673 - loss: 0.0808
Epoch 15/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9686 - loss: 0.0781
Epoch 16/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9693 - loss: 0.0753
Epoch 17/26
508/508 - 6s - 12ms/step - binary_accuracy: 0.9709 - loss: 0.0721
Epoch 18/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9714 - loss: 0.0707
Epoch 19/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9720 - loss: 0.0691
Epoch 20/26
508/508 - 6s - 12ms/step - binary_accuracy: 0.9732 - loss: 0.0660
Epoch 21/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9734 - loss: 0.0656
Epoch 22/26
508/508 - 6s - 12ms/step - binary_accuracy: 0.9746 - loss: 0.0627
Epoch 23/26
508/508 - 6s - 11ms/step - binary_accuracy: 0.9746 - loss: 0.0628
Epoch 24/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9758 - loss: 0.0598
Epoch 25/26
508/508 - 5s - 10ms/step - binary_accuracy: 0.9761 - loss: 0.0592
Epoch 26/26
508/508 - 6s - 12ms/step - binary_accuracy: 0.9775 - loss: 0.0563
254/254 - 2s - 6ms/step
| 2         | 0.9374357 | 97.291886 | 2.6648852 | 1.9110519 | 1.2727747 | 23.986820 | 25.648478 | 2.0495128 | 1.8638900 | 0.2912291 | 0.6118528 | 0.0418481 |
Epoch 1/33
488/488 - 6s - 12ms/step - binary_accuracy: 0.8701 - loss: 0.2851
Epoch 2/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9046 - loss: 0.2144
Epoch 3/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9137 - loss: 0.1964
Epoch 4/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9185 - loss: 0.1870
Epoch 5/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9237 - loss: 0.1763
Epoch 6/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9284 - loss: 0.1675
Epoch 7/33
488/488 - 4s - 7ms/step - binary_accuracy: 0.9304 - loss: 0.1627
Epoch 8/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9332 - loss: 0.1562
Epoch 9/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9360 - loss: 0.1504
Epoch 10/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9390 - loss: 0.1447
Epoch 11/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9411 - loss: 0.1398
Epoch 12/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9431 - loss: 0.1349
Epoch 13/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9455 - loss: 0.1314
Epoch 14/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9466 - loss: 0.1277
Epoch 15/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9480 - loss: 0.1256
Epoch 16/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9486 - loss: 0.1233
Epoch 17/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9501 - loss: 0.1207
Epoch 18/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9508 - loss: 0.1190
Epoch 19/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9512 - loss: 0.1179
Epoch 20/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9526 - loss: 0.1156
Epoch 21/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9542 - loss: 0.1126
Epoch 22/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9542 - loss: 0.1112
Epoch 23/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9555 - loss: 0.1094
Epoch 24/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9557 - loss: 0.1080
Epoch 25/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9571 - loss: 0.1058
Epoch 26/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9582 - loss: 0.1034
Epoch 27/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9588 - loss: 0.1008
Epoch 28/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9591 - loss: 0.1007
Epoch 29/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9608 - loss: 0.0976
Epoch 30/33
488/488 - 3s - 6ms/step - binary_accuracy: 0.9613 - loss: 0.0966
Epoch 31/33
488/488 - 6s - 11ms/step - binary_accuracy: 0.9621 - loss: 0.0946
Epoch 32/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9628 - loss: 0.0930
Epoch 33/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9632 - loss: 0.0919
244/244 - 1s - 4ms/step
Epoch 1/33
488/488 - 22s - 46ms/step - binary_accuracy: 0.8755 - loss: 0.2792
Epoch 2/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9065 - loss: 0.2128
Epoch 3/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9141 - loss: 0.1963
Epoch 4/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9193 - loss: 0.1855
Epoch 5/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9232 - loss: 0.1774
Epoch 6/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9262 - loss: 0.1705
Epoch 7/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9294 - loss: 0.1649
Epoch 8/33
488/488 - 5s - 9ms/step - binary_accuracy: 0.9324 - loss: 0.1590
Epoch 9/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9335 - loss: 0.1571
Epoch 10/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9357 - loss: 0.1513
Epoch 11/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9363 - loss: 0.1498
Epoch 12/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9387 - loss: 0.1454
Epoch 13/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9398 - loss: 0.1426
Epoch 14/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9414 - loss: 0.1397
Epoch 15/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9425 - loss: 0.1364
Epoch 16/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9446 - loss: 0.1327
Epoch 17/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9465 - loss: 0.1295
Epoch 18/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9472 - loss: 0.1272
Epoch 19/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9474 - loss: 0.1261
Epoch 20/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9493 - loss: 0.1232
Epoch 21/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9504 - loss: 0.1206
Epoch 22/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9508 - loss: 0.1186
Epoch 23/33
488/488 - 5s - 9ms/step - binary_accuracy: 0.9523 - loss: 0.1163
Epoch 24/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9530 - loss: 0.1142
Epoch 25/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9538 - loss: 0.1117
Epoch 26/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9554 - loss: 0.1093
Epoch 27/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9562 - loss: 0.1084
Epoch 28/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9569 - loss: 0.1067
Epoch 29/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9570 - loss: 0.1065
Epoch 30/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9583 - loss: 0.1039
Epoch 31/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9595 - loss: 0.1004
Epoch 32/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9599 - loss: 0.0998
Epoch 33/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9605 - loss: 0.0979
244/244 - 1s - 5ms/step
Epoch 1/33
488/488 - 8s - 15ms/step - binary_accuracy: 0.8727 - loss: 0.2818
Epoch 2/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9055 - loss: 0.2141
Epoch 3/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9152 - loss: 0.1952
Epoch 4/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9218 - loss: 0.1812
Epoch 5/33
488/488 - 5s - 10ms/step - binary_accuracy: 0.9276 - loss: 0.1692
Epoch 6/33
488/488 - 5s - 9ms/step - binary_accuracy: 0.9299 - loss: 0.1629
Epoch 7/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9337 - loss: 0.1555
Epoch 8/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9350 - loss: 0.1520
Epoch 9/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9372 - loss: 0.1484
Epoch 10/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9397 - loss: 0.1437
Epoch 11/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9402 - loss: 0.1410
Epoch 12/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9432 - loss: 0.1355
Epoch 13/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9441 - loss: 0.1336
Epoch 14/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9456 - loss: 0.1298
Epoch 15/33
488/488 - 3s - 7ms/step - binary_accuracy: 0.9469 - loss: 0.1269
Epoch 16/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9487 - loss: 0.1243
Epoch 17/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9499 - loss: 0.1219
Epoch 18/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9512 - loss: 0.1192
Epoch 19/33
488/488 - 4s - 7ms/step - binary_accuracy: 0.9523 - loss: 0.1162
Epoch 20/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9537 - loss: 0.1136
Epoch 21/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9543 - loss: 0.1119
Epoch 22/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9550 - loss: 0.1102
Epoch 23/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9564 - loss: 0.1084
Epoch 24/33
488/488 - 5s - 9ms/step - binary_accuracy: 0.9567 - loss: 0.1063
Epoch 25/33
488/488 - 5s - 11ms/step - binary_accuracy: 0.9569 - loss: 0.1061
Epoch 26/33
488/488 - 5s - 9ms/step - binary_accuracy: 0.9581 - loss: 0.1037
Epoch 27/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9594 - loss: 0.1020
Epoch 28/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9595 - loss: 0.1001
Epoch 29/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9614 - loss: 0.0967
Epoch 30/33
488/488 - 4s - 8ms/step - binary_accuracy: 0.9616 - loss: 0.0956
Epoch 31/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9619 - loss: 0.0939
Epoch 32/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9641 - loss: 0.0909
Epoch 33/33
488/488 - 4s - 9ms/step - binary_accuracy: 0.9650 - loss: 0.0888
244/244 - 1s - 4ms/step
| 3         | 0.9159589 | 36.293018 | 1.7327236 | 4.1046298 | 5.4962317 | 24.784015 | 32.998205 | 2.1848291 | 1.0929008 | 0.6075448 | 0.1705241 | 0.0195154 |
Epoch 1/39
609/609 - 7s - 12ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 2/39
609/609 - 7s - 11ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 3/39
609/609 - 6s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 4/39
609/609 - 7s - 11ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 5/39
609/609 - 6s - 10ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 6/39
609/609 - 6s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 7/39
609/609 - 6s - 10ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 8/39
609/609 - 6s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 9/39
609/609 - 6s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 10/39
609/609 - 6s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 11/39
609/609 - 6s - 9ms/step - binary_accuracy: 0.7893 - loss: nan
Epoch 12/39
609/609 - 6s - 10ms/step - binary_accuracy: 0.7893 - loss: nan

In [154]:
optimum = nn_opt.max['params']
#learning_rate = optimum['learning_rate']
activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
               'elu', 'exponential', LeakyReLU,'relu']
optimum['activation'] = activationL[round(optimum['activation'])]
optimum['batch_size'] = round(optimum['batch_size'])
optimum['epochs'] = round(optimum['epochs'])
optimum['layers1'] = round(optimum['layers1'])
optimum['layers2'] = round(optimum['layers2'])
optimum['neurons'] = round(optimum['neurons'])
optimizerL = ['Adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','Adam']
#optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
#             'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
#             'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
#             'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
optimum['optimizer'] = optimizerL[round(optimum['optimizer'])] #optimizerD[optimizerL[round(optimum['optimizer'])]]
optimum

{'neurons': 21,
 'kernel': 1.241680678260627,
 'activation': 'tanh',
 'optimizer': 'RMSprop',
 'batch_size': 36,
 'epochs': 49,
 'layers1': 1,
 'layers2': 1,
 'normalization': 1.0,
 'dropout': 0.0,
 'dropout_rate': 0.12604446112307358}

#### Run the model with optimized parameters

In [156]:
epochs = 49
batch_size = 36
neurons = 21 #neurons = #n_hidden
kernel = round(1.24168)
activation = 'tanh'
optimizer = 'RMSprop'
#learning_rate = 0.04111489382986691
batch_size = 36
layers1 = 1
layers2 = 1
normalization = 1
dropout = 0
dropout_rate = 0.12604446112307358

dim1 = len(X_train[0])
dim2 = len(X_train[0][0])
n_classes = 15 # 15 classes because we have 15 columns of labels
model = Sequential()
model.add(Conv1D(neurons, kernel_size=kernel,activation=activation, input_shape=(dim1, dim2)))
if normalization > 0.5:
    model.add(BatchNormalization())
for i in range(layers1):
    model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
if dropout > 0.5:
    model.add(Dropout(dropout_rate, seed=123))
for i in range(layers2):
    model.add(Dense(neurons, activation=activation))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='sigmoid')) # sigmoid so that the pr3ediction probabilities for each row don't have to sum to 1
    #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=["binary_accuracy"]) # binary crossentropy because it's applied to each output node, so each of the 15 stations preds are independent
    # also binary accuracy otherwise it won't be calculated correctly

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2, validation_data=(X_test, y_test))

Epoch 1/49
508/508 - 7s - 14ms/step - binary_accuracy: 0.8836 - loss: 0.2586 - val_binary_accuracy: 0.9018 - val_loss: 0.2237
Epoch 2/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9152 - loss: 0.1948 - val_binary_accuracy: 0.8966 - val_loss: 0.2279
Epoch 3/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9217 - loss: 0.1804 - val_binary_accuracy: 0.9123 - val_loss: 0.1985
Epoch 4/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9267 - loss: 0.1704 - val_binary_accuracy: 0.9219 - val_loss: 0.1818
Epoch 5/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9322 - loss: 0.1595 - val_binary_accuracy: 0.9166 - val_loss: 0.1909
Epoch 6/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9362 - loss: 0.1509 - val_binary_accuracy: 0.9335 - val_loss: 0.1594
Epoch 7/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9422 - loss: 0.1391 - val_binary_accuracy: 0.9417 - val_loss: 0.1450
Epoch 8/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9473 - loss: 0.1287 - val_binary_accuracy: 0.9413 - val_loss: 0.1457
Epoch 9/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9522 - loss: 0.1190 - val_binary_accuracy: 0.9550 - val_loss: 0.1165
Epoch 10/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9566 - loss: 0.1101 - val_binary_accuracy: 0.9599 - val_loss: 0.1063
Epoch 11/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9596 - loss: 0.1031 - val_binary_accuracy: 0.9603 - val_loss: 0.1038
Epoch 12/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9616 - loss: 0.0983 - val_binary_accuracy: 0.9618 - val_loss: 0.0997
Epoch 13/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9630 - loss: 0.0941 - val_binary_accuracy: 0.9652 - val_loss: 0.0923
Epoch 14/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9650 - loss: 0.0895 - val_binary_accuracy: 0.9696 - val_loss: 0.0843
Epoch 15/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9667 - loss: 0.0867 - val_binary_accuracy: 0.9675 - val_loss: 0.0877
Epoch 16/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9681 - loss: 0.0824 - val_binary_accuracy: 0.9703 - val_loss: 0.0803
Epoch 17/49
508/508 - 5s - 11ms/step - binary_accuracy: 0.9691 - loss: 0.0799 - val_binary_accuracy: 0.9709 - val_loss: 0.0794
Epoch 18/49
508/508 - 4s - 8ms/step - binary_accuracy: 0.9697 - loss: 0.0786 - val_binary_accuracy: 0.9732 - val_loss: 0.0734
Epoch 19/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9708 - loss: 0.0756 - val_binary_accuracy: 0.9735 - val_loss: 0.0724
Epoch 20/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9713 - loss: 0.0745 - val_binary_accuracy: 0.9736 - val_loss: 0.0719
Epoch 21/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9723 - loss: 0.0717 - val_binary_accuracy: 0.9724 - val_loss: 0.0770
Epoch 22/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9728 - loss: 0.0709 - val_binary_accuracy: 0.9729 - val_loss: 0.0724
Epoch 23/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9734 - loss: 0.0693 - val_binary_accuracy: 0.9737 - val_loss: 0.0704
Epoch 24/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9740 - loss: 0.0679 - val_binary_accuracy: 0.9709 - val_loss: 0.0770
Epoch 25/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9744 - loss: 0.0672 - val_binary_accuracy: 0.9737 - val_loss: 0.0735
Epoch 26/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9747 - loss: 0.0661 - val_binary_accuracy: 0.9728 - val_loss: 0.0712
Epoch 27/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9752 - loss: 0.0646 - val_binary_accuracy: 0.9756 - val_loss: 0.0686
Epoch 28/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9756 - loss: 0.0639 - val_binary_accuracy: 0.9753 - val_loss: 0.0669
Epoch 29/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9762 - loss: 0.0629 - val_binary_accuracy: 0.9772 - val_loss: 0.0634
Epoch 30/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9763 - loss: 0.0620 - val_binary_accuracy: 0.9734 - val_loss: 0.0730
Epoch 31/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9766 - loss: 0.0616 - val_binary_accuracy: 0.9768 - val_loss: 0.0616
Epoch 32/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9773 - loss: 0.0603 - val_binary_accuracy: 0.9768 - val_loss: 0.0642
Epoch 33/49
508/508 - 5s - 10ms/step - binary_accuracy: 0.9770 - loss: 0.0599 - val_binary_accuracy: 0.9755 - val_loss: 0.0639
Epoch 34/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9777 - loss: 0.0589 - val_binary_accuracy: 0.9773 - val_loss: 0.0619
Epoch 35/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9776 - loss: 0.0580 - val_binary_accuracy: 0.9787 - val_loss: 0.0579
Epoch 36/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9784 - loss: 0.0569 - val_binary_accuracy: 0.9748 - val_loss: 0.0676
Epoch 37/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9789 - loss: 0.0560 - val_binary_accuracy: 0.9756 - val_loss: 0.0651
Epoch 38/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9785 - loss: 0.0559 - val_binary_accuracy: 0.9795 - val_loss: 0.0546
Epoch 39/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9786 - loss: 0.0560 - val_binary_accuracy: 0.9723 - val_loss: 0.0766
Epoch 40/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9789 - loss: 0.0554 - val_binary_accuracy: 0.9712 - val_loss: 0.0799
Epoch 41/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9793 - loss: 0.0540 - val_binary_accuracy: 0.9781 - val_loss: 0.0589
Epoch 42/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9795 - loss: 0.0536 - val_binary_accuracy: 0.9763 - val_loss: 0.0634
Epoch 43/49
508/508 - 3s - 6ms/step - binary_accuracy: 0.9797 - loss: 0.0532 - val_binary_accuracy: 0.9813 - val_loss: 0.0521
Epoch 44/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9800 - loss: 0.0528 - val_binary_accuracy: 0.9792 - val_loss: 0.0562
Epoch 45/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9798 - loss: 0.0525 - val_binary_accuracy: 0.9822 - val_loss: 0.0511
Epoch 46/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9798 - loss: 0.0526 - val_binary_accuracy: 0.9773 - val_loss: 0.0610
Epoch 47/49
508/508 - 4s - 7ms/step - binary_accuracy: 0.9806 - loss: 0.0516 - val_binary_accuracy: 0.9813 - val_loss: 0.0536
Epoch 48/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9803 - loss: 0.0513 - val_binary_accuracy: 0.9818 - val_loss: 0.0510
Epoch 49/49
508/508 - 3s - 7ms/step - binary_accuracy: 0.9808 - loss: 0.0507 - val_binary_accuracy: 0.9821 - val_loss: 0.0519

In [158]:
preds = model.predict(X_test).round()

147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

In [160]:
print(metrics.classification_report(y_test.values, preds, zero_division = np.nan, target_names = locations))

              precision    recall  f1-score   support

      KASSEL       0.99      0.98      0.99      1299
   STOCKHOLM       0.97      0.98      0.97      1755
      DEBILT       0.96      0.98      0.97      1459
    HEATHROW       1.00      0.97      0.98      1044
  MAASTRICHT       1.00      0.94      0.97      1135
  DUSSELDORF       0.96      0.97      0.96      1140
      MADRID       1.00      0.96      0.98       308
    MUNCHENB       0.97      0.92      0.94      1425
    BELGRADE       1.00      0.97      0.98      1156
   SONNBLICK       0.98      0.99      0.98      2256
    BUDAPEST       0.92      0.88      0.90      1129
   LJUBLJANA       0.84      0.87      0.86       738
    VALENTIA        nan       nan       nan         0
       BASEL       0.97      0.98      0.98       941
        OSLO       0.00       nan      0.00         0

   micro avg       0.96      0.96      0.96     15785
   macro avg       0.90      0.95      0.89     15785
weighted avg       0.97      0.96      0.96     15785
 samples avg       0.95      0.95      0.93     15785

Improved from the first CNN run! I would not say that this is overfit. There is room for improvement but need the computational resources to do so.

### Reference

In [124]:
data = {
    "Problem Type": [
        "Binary Classification",
        "Multi-Class Classification",
        "Multi-Class (Sparse)",
        "Multi-Label Classification"
    ],
    "Output Neurons": [
        "1",
        "N (number of classes)",
        "N (number of classes)",
        "N (number of labels)"
    ],
    "Activation Function": [
        "Sigmoid",
        "Softmax",
        "Softmax",
        "Sigmoid"
    ],
    "Common Loss Function": [
        "Binary Cross-Entropy",
        "Categorical Cross-Entropy",
        "Sparse Categorical Cross-Entropy",
        "Binary Cross-Entropy"
    ],
    "Target Label Format": [
        "0 or 1",
        "One-Hot Encoded (e.g., [0,1,0])",
        "Integer Encoded (e.g., 1)",
        "Binary vector (e.g., [0,1,1])"
    ]
}

# Create the DataFrame
df_summary = pd.DataFrame(data)
df_summary

,Problem Type,Output Neurons,Activation Function,Common Loss Function,Target Label Format
0,Binary Classification,1,Sigmoid,Binary Cross-Entropy,0 or 1
1,Multi-Class Classification,N (number of classes),Softmax,Categorical Cross-Entropy,"One-Hot Encoded (e.g., [0,1,0])"
2,Multi-Class (Sparse),N (number of classes),Softmax,Sparse Categorical Cross-Entropy,"Integer Encoded (e.g., 1)"
3,Multi-Label Classification,N (number of labels),Sigmoid,Binary Cross-Entropy,"Binary vector (e.g., [0,1,1])"

In [ ]:
# we have a binary classification problem but it's set up like a multi-label classification problem because the 15 stations are separated